# Dataset Overview
## Soil and Environmental Data:
* Soil_Type: The classification of soil (e.g., Clay, Silt, Sandy, Loamy). Different textures hold water and nutrients at different rates.

* Soil_pH: A measure of the acidity or alkalinity of the soil. It is critical because it dictates how well nutrients are available to plant roots.

* Soil_Moisture: The percentage of water content currently present in the soil. This is a direct input for determining if irrigation is required.

* Organic_Carbon: A proxy for soil fertility and organic matter content. Higher values generally indicate healthier, more productive soil.

* Electrical_Conductivity: Measures the soil's ability to conduct electricity, which is used to estimate the concentration of dissolved salts in the soil (salinity).

* Temperature_C: The temperature of the soil or immediate air environment, which directly impacts the rate of evaporation and plant transpiration.

* Humidity: The amount of water vapor in the air. High humidity generally slows down water loss from plants and soil.

* Rainfall_mm: The amount of precipitation recorded. This is a primary source of water that significantly offsets the need for artificial irrigation.

* Sunlight_Hours: The duration of direct sun exposure, which dictates the rate of photosynthesis and, consequently, the plant’s water consumption.

* Wind_Speed_kmh: Faster winds increase the rate of evaporation from both the soil and plant leaves, often increasing the urgency of irrigation.
## Crop and Management Data
* Crop_Type: The species of crop being grown (Wheat, Maize, Cotton, Sugarcane). Each has different water requirements based on its biological needs.

* Crop_Growth_Stage: The current stage of the plant's life cycle (Sowing, Vegetative, Flowering, Harvest). Water needs fluctuate drastically depending on the stage.

* Season: The agricultural season (Rabi, Kharif, Zaid). This is linked to typical weather patterns and regional availability of water.

* Irrigation_Type: The method used to apply water (Rainfed, Drip, Canal). Different methods have different efficiencies.

* Water_Source: Where the irrigation water is coming from (Groundwater, Reservoir, River, Rainwater), which affects availability and cost.

* Field_Area_hectare: The total size of the agricultural plot. This helps calculate the total volume of water required.

* Mulching_Used: Indicates if the soil is covered (with organic material or plastic) to prevent evaporation and retain soil moisture.

* Previous_Irrigation_mm: The amount of water applied in the last irrigation cycle. This helps the model understand the current state of water saturation.

* Region: The geographic location (North, South, East, Central), which acts as a proxy for regional climate variations and soil types.

* Irrigation_Need: This is the Target Variable. It classifies the required amount of irrigation (Low, Medium, High) that the model is intended to predict based on all the inputs above.

In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\PRAVALLIKA\Downloads\predicting irrigation need\Orginal.csv")
df

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Silt,7.01,26.67,0.86,0.76,27.61,52.20,1075.12,7.41,19.66,Sugarcane,Sowing,Kharif,Drip,Groundwater,2.62,Yes,92.44,South,Low
9996,Clay,5.40,49.44,0.90,1.19,34.03,52.31,1591.84,9.86,5.66,Maize,Sowing,Kharif,Rainfed,Groundwater,4.87,No,15.46,South,Low
9997,Loamy,4.97,60.63,0.99,1.30,36.68,68.16,2384.87,10.75,13.40,Potato,Harvest,Kharif,Canal,Groundwater,10.08,Yes,116.36,North,Low
9998,Loamy,7.12,44.33,1.56,1.08,31.50,64.83,2397.01,4.03,3.05,Sugarcane,Harvest,Kharif,Rainfed,Reservoir,11.11,Yes,118.17,East,Low
9999,Sandy,5.65,62.25,1.48,3.00,35.71,45.33,177.69,10.93,12.32,Potato,Harvest,Kharif,Canal,Rainwater,11.32,No,98.88,North,Medium

In [2]:
df.corr(numeric_only=True)

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
Soil_pH,1.000000,-0.014067,-0.011119,0.011084,0.000129,-0.011244,0.002967,-0.009298,0.002630,0.007726,-0.000501
Soil_Moisture,-0.014067,1.000000,-0.018539,-0.020822,-0.005305,0.006601,-0.005875,0.014512,0.002960,-0.004811,-0.009195
Organic_Carbon,-0.011119,-0.018539,1.000000,0.011628,0.007155,-0.011748,-0.010832,-0.011462,0.021523,-0.024825,0.003107
Electrical_Conductivity,0.011084,-0.020822,0.011628,1.000000,-0.003715,-0.000236,-0.013536,0.003429,-0.009394,0.009923,0.010360
Temperature_C,0.000129,-0.005305,0.007155,-0.003715,1.000000,-0.008693,0.007771,0.002778,-0.008468,0.013636,0.003862
Humidity,-0.011244,0.006601,-0.011748,-0.000236,-0.008693,1.000000,-0.007395,0.016399,0.013205,0.005647,-0.002175
Rainfall_mm,0.002967,-0.005875,-0.010832,-0.013536,0.007771,-0.007395,1.000000,-0.014846,0.003926,-0.016848,0.000530
Sunlight_Hours,-0.009298,0.014512,-0.011462,0.003429,0.002778,0.016399,-0.014846,1.000000,-0.000002,-0.012491,0.002206
Wind_Speed_kmh,0.002630,0.002960,0.021523,-0.009394,-0.008468,0.013205,0.003926,-0.000002,1.000000,0.005310,-0.002884
Field_Area_hectare,0.007726,-0.004811,-0.024825,0.009923,0.013636,0.005647,-0.016848,-0.012491,0.005310,1.000000,0.014938
Previous_Irrigation_mm,-0.000501,-0.009195,0.003107,0.010360,0.003862,-0.002175,0.000530,0.002206,-0.002884,0.014938,1.000000

# EDA

In [3]:
df.columns

Index(['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage',
       'Season', 'Irrigation_Type', 'Water_Source', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_mm', 'Region', 'Irrigation_Need'],
      dtype='str')

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Soil_Type                10000 non-null  str
 1   Soil_pH                  10000 non-null  float64
 2   Soil_Moisture            10000 non-null  float64
 3   Organic_Carbon           10000 non-null  float64
 4   Electrical_Conductivity  10000 non-null  float64
 5   Temperature_C            10000 non-null  float64
 6   Humidity                 10000 non-null  float64
 7   Rainfall_mm              10000 non-null  float64
 8   Sunlight_Hours           10000 non-null  float64
 9   Wind_Speed_kmh           10000 non-null  float64
 10  Crop_Type                10000 non-null  str
 11  Crop_Growth_Stage        10000 non-null  str
 12  Season                   10000 non-null  str
 13  Irrigation_Type          10000 non-null  str
 14  Water_Source             10000 non-null  str
 15  Field_Area_hectare       10000 non-null  float64
 16  Mulching_Used            10000 non-null  str
 17  Previous_Irrigation_mm   10000 non-null  float64
 18  Region                   10000 non-null  str
 19  Irrigation_Need          10000 non-null  str
dtypes: float64(11), str(9)
memory usage: 1.5 MB

In [6]:
df.corr(numeric_only=True)

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
Soil_pH,1.000000,-0.014067,-0.011119,0.011084,0.000129,-0.011244,0.002967,-0.009298,0.002630,0.007726,-0.000501
Soil_Moisture,-0.014067,1.000000,-0.018539,-0.020822,-0.005305,0.006601,-0.005875,0.014512,0.002960,-0.004811,-0.009195
Organic_Carbon,-0.011119,-0.018539,1.000000,0.011628,0.007155,-0.011748,-0.010832,-0.011462,0.021523,-0.024825,0.003107
Electrical_Conductivity,0.011084,-0.020822,0.011628,1.000000,-0.003715,-0.000236,-0.013536,0.003429,-0.009394,0.009923,0.010360
Temperature_C,0.000129,-0.005305,0.007155,-0.003715,1.000000,-0.008693,0.007771,0.002778,-0.008468,0.013636,0.003862
Humidity,-0.011244,0.006601,-0.011748,-0.000236,-0.008693,1.000000,-0.007395,0.016399,0.013205,0.005647,-0.002175
Rainfall_mm,0.002967,-0.005875,-0.010832,-0.013536,0.007771,-0.007395,1.000000,-0.014846,0.003926,-0.016848,0.000530
Sunlight_Hours,-0.009298,0.014512,-0.011462,0.003429,0.002778,0.016399,-0.014846,1.000000,-0.000002,-0.012491,0.002206
Wind_Speed_kmh,0.002630,0.002960,0.021523,-0.009394,-0.008468,0.013205,0.003926,-0.000002,1.000000,0.005310,-0.002884
Field_Area_hectare,0.007726,-0.004811,-0.024825,0.009923,0.013636,0.005647,-0.016848,-0.012491,0.005310,1.000000,0.014938
Previous_Irrigation_mm,-0.000501,-0.009195,0.003107,0.010360,0.003862,-0.002175,0.000530,0.002206,-0.002884,0.014938,1.000000

In [7]:
df.describe()

,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.487857,36.969207,0.944731,1.791963,26.991423,60.080339,1252.499420,7.518538,10.163545,7.598024,59.864122
std,0.979963,16.430845,0.372406,0.984202,8.664074,20.187973,715.582201,2.016077,5.670923,4.233919,34.483722
min,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,5.640000,22.860000,0.620000,0.940000,19.460000,42.855000,634.155000,5.760000,5.160000,3.950000,30.160000
50%,6.470000,37.240000,0.950000,1.780000,27.090000,60.040000,1250.335000,7.560000,10.190000,7.540000,59.630000
75%,7.350000,50.940000,1.260000,2.650000,34.500000,77.705000,1880.265000,9.260000,15.100000,11.202500,90.030000
max,8.200000,65.000000,1.600000,3.500000,42.000000,95.000000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [8]:
bins = [0, 20, 40, 55, 100]
labels = ['Extremely_Dry', 'Slightly_Dry', 'Optimal', 'Saturated']
df['Soil_Moisture'] = pd.cut(df['Soil_Moisture'], bins=bins, labels=labels)   # amount of water prestent

In [9]:
bins = [0,177, 700, 1400,2500]
labels = ['Low_Rainfall', 'Moderate', 'High', 'Very_High']
df['Rainfall_mm'] = pd.cut(df['Rainfall_mm'],bins=bins,labels=labels)

In [10]:
df['Organic_Carbon'] = pd.to_numeric(df['Organic_Carbon'])
bins = [0, 0.5, 1.5, 10.0]                 # indicates soil health whether it is taking water correctly holds nitrogen, phosphorus, and potassium, 
labels = ['Tired', 'Average', 'Rich']      # preventing them from washing away with irrigation or rain.      
df['Organic_Carbon'] = pd.cut(df['Organic_Carbon'], bins=bins, labels=labels)

In [11]:
df['Electrical_Conductivity'] = pd.to_numeric(df['Electrical_Conductivity'])
bins = [0.0, 2.0, 4.0]                                                 
labels = ['Optimal', 'Caution']
df['Electrical_Conductivity'] = pd.cut(df['Electrical_Conductivity'],bins=bins,labels=labels)  # amount of salt present in soil

In [12]:
df["Wind_Speed_kmh"]=pd.to_numeric(df["Wind_Speed_kmh"])
bins = [0, 5, 19, 38, 150]
labels = ['Calm', 'Light_Breeze', 'Windy', 'High_Wind']
df["Wind_Speed_kmh"]=pd.cut(df["Wind_Speed_kmh"],bins=bins,labels=labels)

In [13]:
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,Slightly_Dry,Tired,Caution,21.90,31.19,High,4.01,Calm,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,Optimal,Tired,Optimal,36.50,26.01,High,10.72,Light_Breeze,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,Optimal,Average,Caution,41.83,76.41,Very_High,7.75,Windy,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,Extremely_Dry,Rich,Optimal,37.22,43.32,Moderate,8.90,Light_Breeze,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,Extremely_Dry,Average,Caution,22.38,86.44,Very_High,10.39,Light_Breeze,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

# Dropping irrelevant features

In [14]:
df.drop(columns=["Region","Field_Area_hectare"],inplace=True)

# Seggregating input and output features

In [15]:
x=df.drop(columns=["Irrigation_Need"])
y=df["Irrigation_Need"]

In [16]:
x.head(3)

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Mulching_Used,Previous_Irrigation_mm
0,Clay,6.14,Slightly_Dry,Tired,Caution,21.90,31.19,High,4.01,Calm,Wheat,Vegetative,Rabi,Rainfed,Reservoir,Yes,1.98
1,Silt,6.41,Optimal,Tired,Optimal,36.50,26.01,High,10.72,Light_Breeze,Maize,Flowering,Zaid,Canal,Groundwater,Yes,33.56
2,Sandy,7.71,Optimal,Average,Caution,41.83,76.41,Very_High,7.75,Windy,Cotton,Harvest,Rabi,Drip,Reservoir,Yes,34.62

In [17]:
y.head()

0       Low
1    Medium
2       Low
3    Medium
4    Medium
Name: Irrigation_Need, dtype: str

In [18]:
y.value_counts()

Irrigation_Need
Low       5864
Medium    3800
High       336
Name: count, dtype: int64

In [19]:
df.describe()

,Soil_pH,Temperature_C,Humidity,Sunlight_Hours,Previous_Irrigation_mm
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.487857,26.991423,60.080339,7.518538,59.864122
std,0.979963,8.664074,20.187973,2.016077,34.483722
min,4.800000,12.000000,25.000000,4.000000,0.020000
25%,5.640000,19.460000,42.855000,5.760000,30.160000
50%,6.470000,27.090000,60.040000,7.560000,59.630000
75%,7.350000,34.500000,77.705000,9.260000,90.030000
max,8.200000,42.000000,95.000000,11.000000,119.990000

In [20]:
df.describe(include="str")

,Soil_Type,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Mulching_Used,Irrigation_Need
count,10000,10000,10000,10000,10000,10000,10000,10000
unique,4,6,4,3,4,4,2,3
top,Sandy,Rice,Harvest,Rabi,Sprinkler,River,No,Low
freq,2536,1711,2581,3383,2527,2528,5013,5864

In [21]:
df.columns

Index(['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage',
       'Season', 'Irrigation_Type', 'Water_Source', 'Mulching_Used',
       'Previous_Irrigation_mm', 'Irrigation_Need'],
      dtype='str')

In [22]:
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Mulching_Used,Previous_Irrigation_mm,Irrigation_Need
0,Clay,6.14,Slightly_Dry,Tired,Caution,21.90,31.19,High,4.01,Calm,Wheat,Vegetative,Rabi,Rainfed,Reservoir,Yes,1.98,Low
1,Silt,6.41,Optimal,Tired,Optimal,36.50,26.01,High,10.72,Light_Breeze,Maize,Flowering,Zaid,Canal,Groundwater,Yes,33.56,Medium
2,Sandy,7.71,Optimal,Average,Caution,41.83,76.41,Very_High,7.75,Windy,Cotton,Harvest,Rabi,Drip,Reservoir,Yes,34.62,Low
3,Clay,5.96,Extremely_Dry,Rich,Optimal,37.22,43.32,Moderate,8.90,Light_Breeze,Wheat,Sowing,Kharif,Canal,Reservoir,Yes,84.03,Medium
4,Clay,7.76,Extremely_Dry,Average,Caution,22.38,86.44,Very_High,10.39,Light_Breeze,Cotton,Sowing,Zaid,Canal,River,No,60.86,Medium

# seggregating columns based on datatype

In [23]:
nominal_cols=['Soil_Type', 'Crop_Type',
       'Season', 'Irrigation_Type', 'Water_Source',
       'Mulching_Used']

In [24]:
df["Crop_Growth_Stage"].unique()

<StringArray>
['Vegetative', 'Flowering', 'Harvest', 'Sowing']
Length: 4, dtype: str

In [25]:
ordinal_cols=["Crop_Growth_Stage",'Soil_Moisture', 'Organic_Carbon', 'Rainfall_mm',
       'Electrical_Conductivity','Wind_Speed_kmh']
order=["Sowing","Vegetative","Flowering","Harvest"]

In [26]:
categorical_cols=['Soil_Type', 'Crop_Type',
       'Season', 'Irrigation_Type', 'Water_Source',
       'Mulching_Used',"Crop_Growth_Stage"]

In [27]:
numeric_cols=['Soil_pH', 'Temperature_C', 'Humidity',
       'Sunlight_Hours','Previous_Irrigation_mm']

# Creating Pipeline

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [29]:
numerical_pipeline=Pipeline([("scaling",StandardScaler())])
numerical_pipeline

Pipeline(steps=[('scaling', StandardScaler())])

In [30]:
nominal_pipeline=Pipeline([("Encoding",OneHotEncoder(sparse_output=False))])
nominal_pipeline

Pipeline(steps=[('Encoding', OneHotEncoder(sparse_output=False))])

In [31]:
tar_pipeline=Pipeline([("Encode",LabelEncoder())])

In [32]:
tar=["Irrigation_Need"]

In [33]:
ordinal_pipeline=Pipeline([("Encoding",OrdinalEncoder())])
ordinal_pipeline

Pipeline(steps=[('Encoding', OrdinalEncoder())])

In [34]:
Data_preprocessing = ColumnTransformer(transformers=[
  ("numerical_pipeline",numerical_pipeline,numeric_cols),
    ('Nominal transformation', nominal_pipeline, nominal_cols),
    ("Ordinal transformation", ordinal_pipeline, ordinal_cols)])

Data_preprocessing

ColumnTransformer(transformers=[('numerical_pipeline',
                                 Pipeline(steps=[('scaling',
                                                  StandardScaler())]),
                                 ['Soil_pH', 'Temperature_C', 'Humidity',
                                  'Sunlight_Hours', 'Previous_Irrigation_mm']),
                                ('Nominal transformation',
                                 Pipeline(steps=[('Encoding',
                                                  OneHotEncoder(sparse_output=False))]),
                                 ['Soil_Type', 'Crop_Type', 'Season',
                                  'Irrigation_Type', 'Water_Source',
                                  'Mulching_Used']),
                                ('Ordinal transformation',
                                 Pipeline(steps=[('Encoding',
                                                  OrdinalEncoder())]),
                                 ['Crop_Growth_Stage', 'Soil_Moisture',
                                  'Organic_Carbon', 'Rainfall_mm',
                                  'Electrical_Conductivity',
                                  'Wind_Speed_kmh'])])

# Model Building and Evaluation

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=18)

In [37]:
from imblearn.over_sampling import SMOTE

In [38]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,classification_report

In [39]:
import warnings
warnings.filterwarnings("ignore")

# 1. Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
from imblearn.pipeline import Pipeline as ImbPipeline

In [42]:
lor=Pipeline([("Data Preprocessing",Data_preprocessing),
                 ("Model",LogisticRegression(class_weight="balanced"))])
lor.fit(x_train,y_train)
y_pred=lor.predict(x_test)

print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.5255
precision_score 0.6141537281897492
recall_score 0.5255

In [43]:
train_pred = lor.predict(x_train)
y_pred = lor.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.5439
Test accuracy Score: 0.5255

# 2. KNeighborsclassifier

In [44]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
knn=Pipeline([("Data Preprocessing",Data_preprocessing),
             ("Model",KNeighborsClassifier(weights="uniform"))])
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.6775
precision_score 0.6616998560360905
recall_score 0.6775

In [46]:
train_pred = knn.predict(x_train)
y_pred = knn.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.7935
Test accuracy Score: 0.6775

#  3. DecisionTreeClassifier

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
dtc=Pipeline([("Data Preprocessing",Data_preprocessing),
            ("Model",DecisionTreeClassifier(class_weight="balanced"))])
dtc.fit(x_train,y_train)
y_pred=dtc.predict(x_test)
print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.792
precision_score 0.7921939058821483
recall_score 0.792

In [49]:
train_pred = dtc.predict(x_train)
y_pred = dtc.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 1.0000
Test accuracy Score: 0.7920

# 4. SVM

In [50]:
from sklearn.svm import SVC

In [51]:
svm=Pipeline([("Data Preprocessing",Data_preprocessing),
             ("Model",SVC(class_weight='balanced'))])
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.7945
precision_score 0.8137478039940325
recall_score 0.7945

In [52]:
train_pred = svm.predict(x_train)
y_pred = svm.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.8394
Test accuracy Score: 0.7945

# 5. Random Forest

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
rfc=Pipeline([("Data Preprocessing",Data_preprocessing),
             ("Model",RandomForestClassifier(class_weight="balanced"))])
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)
print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.8165
precision_score 0.8088225570138716
recall_score 0.8165

In [55]:
train_pred = rfc.predict(x_train)
y_pred = rfc.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 1.0000
Test accuracy Score: 0.8165

# 6. AdaBoost

In [56]:
from sklearn.ensemble import AdaBoostClassifier

In [57]:
adaboost=ImbPipeline([("Data Preprocessing",Data_preprocessing), ('smote', SMOTE(random_state=42)),
             ("Model",AdaBoostClassifier())])
adaboost.fit(x_train,y_train)
y_pred=adaboost.predict(x_test)
print("accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

accuracy 0.787
precision_score 0.8011061927814517
recall_score 0.787

In [58]:
train_pred = adaboost.predict(x_train)
y_pred = adaboost.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.7889
Test accuracy Score: 0.7870

# 7. XGB

In [59]:
from xgboost import XGBClassifier

In [60]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [97]:
y=le.fit_transform(y)
y

array([1, 2, 1, ..., 1, 1, 2], shape=(10000,))

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=18)

In [63]:
xgboost=Pipeline([("Data Preprocessing",Data_preprocessing),
             ("Model",XGBClassifier(objective='multi:softmax',n_classes=3, scale_pos_weight="Balancing of positive and negative weights"))])
xgboost.fit(x_train,y_train)
y_pred=xgboost.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

Accuracy 0.848
precision_score 0.8453365079906078
recall_score 0.848

In [64]:
train_pred = xgboost.predict(x_train)
y_pred = xgboost.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.9979
Test accuracy Score: 0.8480

# Cross Validation

In [65]:
from sklearn.model_selection import KFold,cross_val_score

In [66]:
kfcv=KFold(n_splits=5,shuffle=True,random_state=18)

In [68]:
cross_val_score(estimator=xgboost,
               X=x,
               y=y,
               scoring='accuracy',
               cv=kfcv).mean()

np.float64(0.8502000000000001)

# Hyper-parameter Tuning

In [69]:
from xgboost import XGBClassifier

In [73]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'Model__n_estimators': [100, 200],
    'Model__max_depth': [3, 5, 7],
    'Model__learning_rate': [0.01, 0.1, 0.2],
}

grid_xgb = GridSearchCV(
    estimator=xgboost,
    param_grid=param_grid,
    cv=kfcv,
    scoring='r2',
    n_jobs=-1
)

In [74]:
grid_xgb.fit(x_train, y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=18, shuffle=True),
             estimator=Pipeline(steps=[('Data Preprocessing',
                                        ColumnTransformer(transformers=[('numerical_pipeline',
                                                                         Pipeline(steps=[('scaling',
                                                                                          StandardScaler())]),
                                                                         ['Soil_pH',
                                                                          'Temperature_C',
                                                                          'Humidity',
                                                                          'Sunlight_Hours',
                                                                          'Previous_Irrigation_mm']),
                                                                        ('Nominal '
                                                                         'transformation',
                                                                         Pipeline(steps=[('Encoding',
                                                                                          On...
                                                      max_cat_threshold=None,
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_classes=3,
                                                      n_estimators=None,
                                                      n_jobs=None, ...))]),
             n_jobs=-1,
             param_grid={'Model__learning_rate': [0.01, 0.1, 0.2],
                         'Model__max_depth': [3, 5, 7],
                         'Model__n_estimators': [100, 200]},
             scoring='r2')

In [75]:
print("Best Parameters:", grid_xgb.best_params_)
print("Best CV Score:", grid_xgb.best_score_)

Best Parameters: {'Model__learning_rate': 0.1, 'Model__max_depth': 5, 'Model__n_estimators': 100}
Best CV Score: 0.2937918649179586

In [79]:
xgboost_model=Pipeline([("Data Preprocessing",Data_preprocessing),
             ("Model",XGBClassifier(objective='multi:softmax',n_classes=3, scale_pos_weight="Balancing of positive and negative weights",learning_rate=0.1,max_depth= 5, n_estimators=100))])
xgboost_model.fit(x_train,y_train)
y_pred=xgboost_model.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average='weighted'))
print("recall_score",recall_score(y_test,y_pred,average='weighted'))

Accuracy 0.865
precision_score 0.8637059117097174
recall_score 0.865

In [80]:
train_pred = xgboost_model.predict(x_train)
y_pred = xgboost_model.predict(x_test)

train_r2 = accuracy_score(y_train, train_pred)
test_r2 = accuracy_score(y_test, y_pred)

print(f"Training accuracy Score: {train_r2:.4f}")
print(f"Test accuracy Score: {test_r2:.4f}")

Training accuracy Score: 0.9055
Test accuracy Score: 0.8650

In [81]:
final_pipeline = xgboost_model.fit(x, y)
final_pipeline

Pipeline(steps=[('Data Preprocessing',
                 ColumnTransformer(transformers=[('numerical_pipeline',
                                                  Pipeline(steps=[('scaling',
                                                                   StandardScaler())]),
                                                  ['Soil_pH', 'Temperature_C',
                                                   'Humidity', 'Sunlight_Hours',
                                                   'Previous_Irrigation_mm']),
                                                 ('Nominal transformation',
                                                  Pipeline(steps=[('Encoding',
                                                                   OneHotEncoder(sparse_output=False))]),
                                                  ['Soil_Type', 'Crop_Type',
                                                   'Season', 'Irri...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_classes=3, n_estimators=100, n_jobs=None, ...))])

In [ ]:
import pickle

with open(r"C:\Users\PRAVALLIKA\p\Irrigation-.pkl", "wb") as Irr:
    pickle.dump(final_pipeline, Irr)

with open(r"C:\Users\PRAVALLIKA\p\Irrigation-.pkl", 'rb') as Irrigation:
    model = pickle.load(Irrigation)

# prediction

In [105]:

sample_input = {
    'Soil_Type': 'Clay',
    'Soil_pH': 6.14,
    'Soil_Moisture': 'Slightly_Dry',
    'Organic_Carbon': 'Tired',
    'Electrical_Conductivity': 'Caution',
    'Temperature_C': 21.90,
    'Humidity': 31.19,
    'Rainfall_mm': 'High',
    'Sunlight_Hours':4.01,
    'Wind_Speed_kmh':'Calm',
    'Crop_Type': 'Wheat',
    'Crop_Growth_Stage': 'Vegetative',
    'Season': 'Rabi',
    'Irrigation_Type': 'Rainfed',
    'Water_Source': 'Reservoir',
    'Mulching_Used': 'Yes',
    'Previous_Irrigation_mm': 1.98
    }

In [106]:
input_df = pd.DataFrame([sample_input])
prediction = final_pipeline.predict(input_df)
print("Predicted Output:", prediction[0])

Predicted Output: 1